spring:
  application:
    name: api-gateway

eureka:
  client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    order:
      path: /order/**
      serviceId: order-service
    product:
      path: /product/**
      serviceId: product-service

server:
  port: 8084